repository:
  path: /home/ayziochatbot/repositories/Ayzio-Chat-Bot
  name: Ayzio-Chat-Bot
  checked-out-branch: null  # The system could not find any branches for this repository.
  remote-url: https://github.com/Yapayzeka-io-Topics/Ayzio-Chat-Bot.git
